[data_parameters]
num_classes = 5

[model_parameters]
model_name = "facebook/detr-resnet-101"
batch_size = 32
epochs = 30
learning_rate = 0.0006

[optimizer_parameters]
eta_min = 1e-6

[meta_parameters]
path_to_data = ""
path_to_metadata = ""
